name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file:
          - test_chat.py
          - test_error_handling.py
          - test_folders.py
          - test_health_endpoint.py
          - test_individual_endpoints.py
          - test_integration.py
          - test_models.py
          - test_opencode_client.py
          - test_sessions.py
          - test_stream.py
          #- test_tool_call_parsing.py
          - test_workspaces.py

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm install
          npm install -g opencode-ai@latest

      - name: Test ${{ matrix.test-file }}
        run: |
          npm run test:install
          npm run test -- -n 0 -s -x tests/${{ matrix.test-file }}
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

  test:
    runs-on: ubuntu-latest
    needs: [test-matrix]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.test-matrix.result }}" == "success" ]]; then
            echo "All tests passed!"
            exit 0
          else
            echo "Some tests failed!"
            exit 1
          fi
