name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm install
          npm run test:install
          npm install -g opencode-ai@latest

      - name: Test
        run: npm run test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Test Leak Detection
        run: |
          # Run leak tests but don't fail the build if they fail (they're optional)
          echo "Running leak detection tests (these are optional and won't fail the build)"
          npm run test:leak; TEST_EXIT_CODE=$?
          case $TEST_EXIT_CODE in
            0)
              echo "Leak tests completed successfully"
              ;;
            5)
              echo "Leak tests completed - no tests were collected (all skipped as expected)"
              ;;
            *)
              echo "Leak tests completed with exit code $TEST_EXIT_CODE (this is acceptable as these tests are optional)"
              ;;
          esac
          # Always exit with success since these are optional tests
          exit 0
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}